commande_homepage:
    path:     /
    defaults: { _controller: CommandeBundle:Default:index }
produit:
    path:     /produit
    defaults: { _controller: CommandeBundle:Produit:List}
panier:
    path:     /panier
    defaults: { _controller: CommandeBundle:Panier:panier}
ajout:
    pattern:  /ajout/{id}
    defaults: { _controller: CommandeBundle:Panier:ajout }